poll_interval_seconds: 1
metric_stores:
  - name: monitoring
    type: prometheus
    prometheus:
      url: http://g10_prometheus:9090
autoscale_rules:
  - service_name: g10_web
    scale_min: 1
    scale_max: 5
    scale_step: 1
    metric_store: monitoring
    ###### cpu utilization ######
    metric_query: sum(rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_task_name=~'.+'}[30s]))BY(container_label_com_docker_swarm_service_name,instance)*100
    scale_up_threshold: 1000
    scale_down_threshold: 500

    ###### memory usage ######
    # metric_query: sum(rate(container_memory_usage_bytes{container_label_com_docker_swarm_task_name=~'.+'}[30s]))BY(container_label_com_docker_swarm_service_name,instance)
    # scale_up_threshold: 2500000000
    # scale_down_threshold: 1000000000

    ###### http_requests ######
    # metric_query: scalar(avg(rate(http_requests_total{job="web"}[30s])))
    # scale_up_threshold: 300
    # scale_down_threshold: 200




