global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
    - targets: ['localhost:9090', 'prometheus:9090']

  - job_name: 'web'
    scrape_interval: 5s
    dns_sd_configs:
    - names:
      - 'tasks.web'
      type: 'A'
      port: 8080

  - job_name: 'cadvisor'
    scrape_interval: 5s
    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8080
  
  - job_name: 'node-exporter'
    scrape_interval: 5s
    dns_sd_configs:
    - names:
      - 'tasks.node-exporter'
      type: 'A'
      port: 9100

  - job_name: 'grafana'
    scrape_interval: 5s
    dns_sd_configs:
    - names:
      - 'tasks.grafana'
      type: 'A'
      port: 3000