global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'web'
    dns_sd_configs:
    - names:
      - 'tasks.web'
      type: 'A'
      port: 8080
